import { NextResponse } from 'next/server';
import { denyUnauthorisedCron } from '@/lib/log/auth';
import { marketSessionRules } from '@/lib/events';
import { todaysMergedEvents } from '@/lib/events/merged';
import { marketNow, marketToday } from '@/lib/time';
import { chicagoNow, isTradingDay } from '@/lib/x/schedule';
import { loadDeskSnapshot } from '@/lib/x/deskData';
import { dueEventHeadsUp, eventHeadsUpText } from '@/lib/x/eventsLine';
import { checkPost, xLen } from '@/lib/x/compose';
import { applyLockedLevels, decideIntraday, lockableLevels, pendingTrigger, phraseUsage } from '@/lib/x/intradaySchedule';
import { readIntradayState, recordEventHeadsUp, recordIntradayPost } from '@/lib/x/intradayStore';
import { postingEnabled, runSlot } from '@/lib/x/run';
import { postTweet, readCredentials } from '@/lib/x/client';
import { appendLog, isPaused, readLog, storeStatus } from '@/lib/x/store';
import type { PostSlot } from '@/lib/x/types';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
export const maxDuration = 60;

/**
 * The intraday X post — a human-style update generated by the Claude API,
 * fired every 30–45 minutes from 9:00 AM to 2:45 PM CT, plus immediately on a
 * level break (below flip, above resistance, below support — once per level per
 * day). See `vercel.json`: the cron fires every 15 minutes across the window,
 * and `decideIntraday` reads the Chicago clock, the random-gap timer and the
 * break state to decide whether *this* firing posts.
 *
 * `?dry=1` / `?preview=1` compose and self-check the next update without posting
 * (the preview ignores the timer). `?force=1` posts now regardless of the timer
 * and the once-a-day ledger.
 */
export async function GET(request: Request) {
  const denied = denyUnauthorisedCron(request);
  if (denied) return denied;

  const params = new URL(request.url).searchParams;
  const dry = params.get('dry') === '1';
  const preview = params.get('preview') === '1';
  const force = params.get('force') === '1';

  const now = new Date();
  const date = marketToday(now);

  if (!isTradingDay(date, marketSessionRules()) && !preview && !force) {
    return NextResponse.json({ status: 'skipped', reason: 'Not a trading day.' });
  }

  const log = await readLog().catch(() => []);
  const usage = phraseUsage(
    log.map((e) => ({ slot: e.slot, outcome: e.outcome, at: e.at, phraseId: e.phraseId })),
    now.getTime() - 5 * 24 * 60 * 60 * 1000,
  );

  const snapshot = await loadDeskSnapshot(now).catch(() => null);
  if (!snapshot) {
    return NextResponse.json({ status: 'skipped', reason: 'Could not read the desk snapshot.' });
  }

  const state = await readIntradayState(date);

  /*
   * Scheduled-event heads-up. Before the ordinary update, check whether a
   * high/medium event (Fed, Treasury, CPI/jobs) is about to start — within 15
   * minutes — and has not been flagged yet, under the day's cap of two. When one
   * is due this firing posts the heads-up instead of a normal update. It is a
   * fixed, safe template (no model call), gated by the same posting switches and
   * deduped per event in the intraday state, so a redeploy or an extra firing
   * never doubles it.
   */
  {
    const events = await todaysMergedEvents(now).catch(() => []);
    const clk = marketNow(now);
    const due = dueEventHeadsUp(events, {
      today: date,
      etMinutesNow: clk.hour * 60 + clk.minute,
      postedKeys: state.eventHeadsUps ?? [],
      postedCount: (state.eventHeadsUps ?? []).length,
    });
    if (due) {
      const text = eventHeadsUpText(due.event, due.minutesUntil);
      const checks = checkPost(text);
      if (preview || dry) {
        return NextResponse.json({ status: 'preview', kind: 'event-headsup', text, checks, key: due.key });
      }
      if (checks.length === 0) {
        if (!postingEnabled()) {
          return NextResponse.json({ status: 'skipped', kind: 'event-headsup', reason: 'Posting is disabled.' });
        }
        if (!force && (await isPaused())) {
          return NextResponse.json({ status: 'skipped', kind: 'event-headsup', reason: 'Posting is paused.' });
        }
        if (!readCredentials()) {
          return NextResponse.json({ status: 'skipped', kind: 'event-headsup', reason: 'X credentials are not configured.' });
        }
        const result = await postTweet(text);
        if (result.ok) {
          await recordEventHeadsUp(date, due.key);
          await appendLog({
            at: now.toISOString(), date, slot: 'intraday', slotKey: due.key,
            text, length: xLen(text), outcome: 'sent', reason: 'Scheduled-event heads-up.',
          });
          return NextResponse.json({ status: 'sent', kind: 'event-headsup', text, key: due.key, store: storeStatus() });
        }
        return NextResponse.json({ status: 'skipped', kind: 'event-headsup', reason: `Heads-up post failed (${result.kind}).` });
      }
      // The heads-up text failed its own self-check (an event name tripped a
      // banned word): skip it quietly and fall through to the normal update.
    }
  }

  // Same locked-levels overlay and wild throttle as the autonomous tick.
  const locked = state.lockedLevels ?? lockableLevels(snapshot);
  const intradaySnapshot = applyLockedLevels(snapshot, locked);
  const lastWild = Date.parse(state.lastWildIso ?? '');
  const allowWild = !Number.isFinite(lastWild) || now.getTime() - lastWild >= 60 * 60 * 1000;
  const decision = decideIntraday(intradaySnapshot, state, now);

  // Preview and force both compose regardless of the timer.
  if (!decision.post && !preview && !force) {
    return NextResponse.json({ status: 'skipped', reason: decision.reason, store: storeStatus() });
  }

  const c = chicagoNow(now);
  const hhmm = `${String(c.hour).padStart(2, '0')}${String(c.minute).padStart(2, '0')}`;
  const trigger = decision.post ? decision.trigger : pendingTrigger(intradaySnapshot, state.triggersPosted);
  const slotKey = decision.post ? decision.slotKey : `intraday-${hhmm}`;
  const slot: PostSlot = {
    kind: 'intraday',
    key: preview ? 'intraday-preview' : slotKey,
    label: trigger ? `Intraday level break (${trigger})` : 'Intraday update',
  };

  const outcome = await runSlot(slot, {
    now,
    force,
    dry: dry || preview,
    ctx: { snapshot: intradaySnapshot, usedPhrases: state.usedPhrases, phraseUsage: usage, allowWild },
  });

  // Advance the pacing timer and mark the break/phrase only on a real send.
  if (outcome.status === 'sent') {
    await recordIntradayPost(date, now, {
      trigger,
      phraseId: outcome.phraseId,
      wild: outcome.wild,
      lockedLevels: locked,
      spyRspVerdict: outcome.spyRspVerdict,
      spyRspMentioned: outcome.spyRspMentioned,
    });
  }

  return NextResponse.json({ ...outcome, trigger, store: storeStatus() });
}
