import { NextResponse } from 'next/server';
import { denyUnauthorisedCron } from '@/lib/log/auth';
import { marketSessionRules } from '@/lib/events';
import { marketToday } from '@/lib/time';
import { chicagoNow, isTradingDay } from '@/lib/x/schedule';
import { loadDeskSnapshot } from '@/lib/x/deskData';
import { applyLockedLevels, decideIntraday, lockableLevels, pendingTrigger, phraseUsage } from '@/lib/x/intradaySchedule';
import { readIntradayState, recordIntradayPost } from '@/lib/x/intradayStore';
import { runSlot } from '@/lib/x/run';
import { readLog, storeStatus } from '@/lib/x/store';
import type { PostSlot } from '@/lib/x/types';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
export const maxDuration = 60;

/**
 * The intraday X post — a human-style update generated by the Claude API,
 * fired every 30–45 minutes from 9:00 AM to 2:45 PM CT, plus immediately on a
 * level break (below flip, above resistance, below support — once per level per
 * day). See `vercel.json`: the cron fires every 15 minutes across the window,
 * and `decideIntraday` reads the Chicago clock, the random-gap timer and the
 * break state to decide whether *this* firing posts.
 *
 * `?dry=1` / `?preview=1` compose and self-check the next update without posting
 * (the preview ignores the timer). `?force=1` posts now regardless of the timer
 * and the once-a-day ledger.
 */
export async function GET(request: Request) {
  const denied = denyUnauthorisedCron(request);
  if (denied) return denied;

  const params = new URL(request.url).searchParams;
  const dry = params.get('dry') === '1';
  const preview = params.get('preview') === '1';
  const force = params.get('force') === '1';

  const now = new Date();
  const date = marketToday(now);

  if (!isTradingDay(date, marketSessionRules()) && !preview && !force) {
    return NextResponse.json({ status: 'skipped', reason: 'Not a trading day.' });
  }

  const log = await readLog().catch(() => []);
  const usage = phraseUsage(
    log.map((e) => ({ slot: e.slot, outcome: e.outcome, at: e.at, phraseId: e.phraseId })),
    now.getTime() - 5 * 24 * 60 * 60 * 1000,
  );

  const snapshot = await loadDeskSnapshot(now).catch(() => null);
  if (!snapshot) {
    return NextResponse.json({ status: 'skipped', reason: 'Could not read the desk snapshot.' });
  }

  const state = await readIntradayState(date);
  // Same locked-levels overlay and wild throttle as the autonomous tick.
  const locked = state.lockedLevels ?? lockableLevels(snapshot);
  const intradaySnapshot = applyLockedLevels(snapshot, locked);
  const lastWild = Date.parse(state.lastWildIso ?? '');
  const allowWild = !Number.isFinite(lastWild) || now.getTime() - lastWild >= 60 * 60 * 1000;
  const decision = decideIntraday(intradaySnapshot, state, now);

  // Preview and force both compose regardless of the timer.
  if (!decision.post && !preview && !force) {
    return NextResponse.json({ status: 'skipped', reason: decision.reason, store: storeStatus() });
  }

  const c = chicagoNow(now);
  const hhmm = `${String(c.hour).padStart(2, '0')}${String(c.minute).padStart(2, '0')}`;
  const trigger = decision.post ? decision.trigger : pendingTrigger(intradaySnapshot, state.triggersPosted);
  const slotKey = decision.post ? decision.slotKey : `intraday-${hhmm}`;
  const slot: PostSlot = {
    kind: 'intraday',
    key: preview ? 'intraday-preview' : slotKey,
    label: trigger ? `Intraday level break (${trigger})` : 'Intraday update',
  };

  const outcome = await runSlot(slot, {
    now,
    force,
    dry: dry || preview,
    ctx: { snapshot: intradaySnapshot, usedPhrases: state.usedPhrases, phraseUsage: usage, allowWild },
  });

  // Advance the pacing timer and mark the break/phrase only on a real send.
  if (outcome.status === 'sent') {
    await recordIntradayPost(date, now, {
      trigger,
      phraseId: outcome.phraseId,
      wild: outcome.wild,
      lockedLevels: locked,
    });
  }

  return NextResponse.json({ ...outcome, trigger, store: storeStatus() });
}
